version: '3.7'
services: 
  db:
    container_name: pushevent_db
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pushevent_db
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    labels:
      name: "Postgres SQL Database"

volumes: 
  postgres_db:
    