version: "3.3"
services: 
  mongo:
    image: mongo:latest
    container_name: pushdb_container
    environment: 
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    labels:
      name: "MongoDB Server"
    volumes: 
      - mongo_db:/var/lib/mongodb/data
volumes: 
  mongo_db:
    